version: '3.7'
services:
  web:
    image: daw22301/daw-apache-php:latest
    build: .
    restart: always
    ports:
      - "80:80"
      - "443:443"
    container_name: daw-apache-php
    links:
      - db
    depends_on:
      - db

  db:
    image: daw22301/daw-mysql:latest
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: proyectonow
    container_name: daw-mysql

  phpmyadmin:
    image: daw22301/daw-phpmyadmin:latest
    restart: always
    links:
      - db
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
    container_name: daw-phpmyadmin


networks:
  bridge:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.17.0.0/17
